### PR TITLE
Try running tests as well

### PR DESCRIPTION
**Pull request by klauer**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by klauer** [comment]
@conda-forge-admin, please rerender

**Comment by klauer** [comment]
Tests pass on Linux/OSX but are failing on windows with what appears to be a fairly consistent message:
```
Traceback (most recent call last):
  File "D:\bld\fuzzysearch_1587057106696\test_tmp\tests\test_substitutions_only.py", line 142, in test_all_different
    self.search(substring, text, max_subs=max_subs),
  File "D:\bld\fuzzysearch_1587057106696\test_tmp\tests\test_substitutions_only.py", line 313, in search
    return hnm_subs(subsequence, sequence, max_subs)
  File "D:\bld\fuzzysearch_1587057106696\_test_env\lib\site-packages\fuzzysearch\substitutions_only.py", line 23, in has_near_match_substitutions
    for start_index in search_exact(subsequence, sequence):
  File "D:\bld\fuzzysearch_1587057106696\_test_env\lib\site-packages\fuzzysearch\search_exact.py", line 70, in search_exact
    return search_exact_byteslike(subsequence, sequence,
ValueError: end_index must be non-negative
```

**Comment by klauer** [comment]
Related, perhaps: https://github.com/taleinat/fuzzysearch/issues/13

**Comment by klauer** [comment]
Confusingly, I can't reproduce this with a local windows build of fuzzysearch 0.7.1.

**Comment by taleinat** [comment]
Hi @klauer, I just noticed this now...

I'd be happy to help diagnose the failing tests, but unfortunately their outputs are no longer available on Azure Pipelines.

I have a Windows machine available so I'll see if the tests happen to fail for me as well...

**Comment by klauer** [comment]
@taleinat - no problem. Fixing the merge conflict here should trigger another build - let me know if you still can't see the output from there.

For what it's worth, I had tried a while back to reproduce this locally on a Windows machine and couldn't.

**Comment by taleinat** [comment]
So, on the Windows build, for some reason at least one of the Cython modules appears very broken. I'm can't tell why, yet, as I too cannot reproduce this failure on my Windows machine.

BTW, the Cython modules have their C code included in the source. Cython is not required at any stage.

**Comment by klauer** [comment]
Interesting - I don't think I had noticed the inclusion of the cython-generated C source files. Is that common for cython projects?

I might try a `make clean-cython cython && setup.py build` out of curiosity to see if it affects the windows builds in this PR.

**Comment by taleinat** [comment]
I've started working on this. The issue doesn't seem to be with the Cython-based extensions.

**Comment by taleinat** [comment]
@klauer, I've fixed what appears to be the source of this issue. The fix is available in version 0.7.3 which I've just released. Let's try this again with the new version.

**Comment by klauer** [comment]
Great! Will bump the version and retry.

**Comment by taleinat** [comment]
Looks like it's still failing :(

I see build warnings that I don't get when building locally on Windows. I'm using a slightly different version of MSCV: 14.11.25503 vs. version 14.16.27023 used in the Azure DevOps job, perhaps that's the reason?

**Comment by klauer** [comment]
Hmm :/ it might be, but I don't believe we have control over that in the conda recipes. What's the differing warning you noticed?

Happy to try any other fixes you can think of - patches can be relatively easily applied on top of v0.7.3 without touching the source repo.

**Comment by taleinat** [comment]
Is this being built with a standard version of Python or is it somehow customized?

Is there a way to try this manually in a similar environment so that I can to diagnose this?

**Comment by klauer** [comment]
In the feedstock, there's `build-locally.py`: https://conda-forge.org/docs/maintainer/updating_pkgs.html#testing-changes-locally which relies on Docker. Windows, sadly, is a different beast: https://conda-forge.org/docs/maintainer/knowledge_base.html#local-testing

conda-forge releases its own Python builds (as does anaconda), but I don't believe they're modified from stock in any significant way.

**Comment by klauer** [comment]
@conda-forge-admin, please rerender

**Comment by klauer** [comment]
@conda-forge-admin, please rerender

**Comment by klauer** [comment]
@conda-forge-admin, please rerender

**Comment by taleinat** [comment]
Version v0.8.0 of fuzzysearch has just been released, which includes a fix for the issue which was breaking these tests.

**Pull request closed without merging**
